### PR TITLE
Dev timber update

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
Sorry for two commits. I just realized now that Jake released a new Timber version 16 hours ago.

**Comment by palaima** [comment]
:+1:

**Comment by vanniktech** [comment]
Could you also then release 0.4.1?

**Comment by palaima** [comment]
I will release 0.5.0 on weekend (new FPS module)

**Comment by palaima** [comment]
:+1:

**Comment by vanniktech** [comment]
Awesome! Thanks for keeping this awesome library alive.

**Pull request merged**
